### ISSUE TITLE
Multiple shift clicks

### ISSUE THREAD

**Issue by nitriques** [shftcl/www-issues#4]
Ref: https://twitter.com/jerome_a_/status/634347714675900416

Currently shift click opens the extracted image in a new window (tab) via window.open, which focuses the newly created window.

Should we try to re-focus the old window (tab) ?

Should it be in the context menu ? 

What are the side effects ?

Shift click wants to remain hassle free, so I do not think that the "user setting" option is viable....

**Comment by hemorej** [comment]
I can't speak for all users who have different preferences about this, but:
- I agree about the "user setting", I think it's a can of worms and a poor solution to such simple applications anyway
- Refocusing the old tab would be cool, one possible side effect here is preserving the scroll position (say if I'm down in a infinite scroll a la Tumblr)
- Context menu is ok, less desirable in my opinion because the main appeal is the simplicity and immediacy of keyboard shortcuts

One idea would be to add a modifier key, ctrl for instance, similar to how ctrl+click opens in a different tab, so that ctrl+shift+click opens in background and shift+click keeps the same behavior. This however brings issues:
- It would require users to remember the additional option
- Affordance, how does anyone actually discover this ? Is it labelled somehow, described somewhere ?
- Like the "user setting" idea, opens the door to other modifiers and adds to the perception of complexity
- This one is personal opinion, but I find shftcl would no longer be just that, the idea at the basis of the extension is altered

**Comment by alexleduc** [comment]
Context menu require 2 clicks + mouse move to find the Shift Click button. Not fast enought
Manually re-focused in the old tab is faster than a switch option in a 'user setting' page.

Click + Shift = extract image and focus in a new tab (default)
Click + Shift + Ctrl  = extract image in a new tab but keep the focus in the current tab.

Can't wait tu use it. :)

**Comment by nitriques** [comment]
What about Click + Shift + Z ?

**Comment by hemorej** [comment]
Why not !
But assuming I didn't know that option existed, how would I find it ?

**Comment by nitriques** [comment]
User discoverability is hard, especially when you try to not mess up anything in the user's UI.

I really like the way Sublime's Package Manager works: It creates a temp file with the content in it and uses the text editor to display it, without adding anything to Sublime's UI.

Based on the fact that this use case is suitable "for experts only", I think that we could
- Show it on the web page.
- Create a proper wiki
- Create a user guide on our website
- Display it in the chrome://extensions/ page
- ...

Feedback please ? :smile:

**Comment by hemorej** [comment]
The first 3 options would require people to leave their current context to find the info elsewhere, assuming they're looking for it. Some people feel safer reading the official literature/website, others (admittedly more "power users") won't. Of the three I prefer the user guide option though.

I also like what this person did [here](https://gist.github.com/nuxlli/1207014) for Sublime

How about displaying it as a tip on the page the extension opens ? That way they'd be sure to find out about it, and find it again in case they forget

**Comment by nitriques** [comment]
> How about displaying it as a tip on the page the extension opens 

When is that ?? The background process starts when you first start the browser and is sometimes paused. The content script is run on each page load.

Did you mean after install ?

**Comment by hemorej** [comment]
The tab that opens when I shift+click, there's info on the left about color palette, source and such. Perhaps show a "hey did you know that" message there ?

**Comment by nitriques** [comment]
oooooo! I wonder what @alexleduc thinks about this.

**Comment by nitriques** [comment]
Well, it turns out that @alexleduc has some pretty nice ideas for Click + Shift + Z. I'll implement Click + Shift + Ctrl/Cmd

**Comment by nitriques** [comment]
I've just landed it!

After lots of hacking, I've decided to refactored to whole thing and use the chrome api to create the tab (instead of window.open). I feel really dumb right now.

I'll try to release 1.2.0 ASAP.

@alexleduc This should also solve the popup-blocker issues. :rocket:

**Comment by alexleduc** [comment]
Oh wow! Can't wait to use 1.2.0
